package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateGolden(t *testing.T) {
	fixture := `{
  "version": 1,
  "sse": [{"name":"delta","payload":{"properties":[{"name":"delta","type":"string","required":true}]}}],
  "websocket": [
    {"name":"beta_event","payload":{"properties":[{"name":"note","type":"string|null","required":false}]}},
    {"name":"alpha_event","payload":{"properties":[{"name":"count","type":"number","required":true},{"name":"meta","type":"object","required":false}]}}
  ]
}`

	goSource, tsSource, err := Generate(strings.NewReader(fixture))
	require.NoError(t, err)
	assert.Equal(t, `// Code generated by genrealtime; DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

const RealtimeContractVersion = 1

type EventType string

// RealtimePtr preserves presence for optional primitive payload fields,
// including explicit zero and false values.
func RealtimePtr[T any](value T) *T { return &value }

type realtimeNumber interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~float32 | ~float64
}

func RealtimeInt64[T realtimeNumber](value T) *int64 {
	converted := int64(value)
	return &converted
}

func RealtimeFloat64[T realtimeNumber](value T) *float64 {
	converted := float64(value)
	return &converted
}

func RealtimeArray[T any](values []T) []any {
	result := make([]any, len(values))
	for index := range values {
		result[index] = values[index]
	}
	return result
}

func MustRealtimeObject(value any) map[string]any {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("encode realtime object: %v", err))
	}
	var result map[string]any
	if err := json.Unmarshal(encoded, &result); err != nil {
		panic(fmt.Sprintf("decode realtime object: %v", err))
	}
	return result
}

const (
	EventAlphaEvent EventType = "alpha_event"
	EventBetaEvent  EventType = "beta_event"
)

const (
	SSEEventDelta = "delta"
)

type AlphaEventPayload struct {
	Count int64          `+"`json:\"count\"`"+`
	Meta  map[string]any `+"`json:\"meta,omitempty\"`"+`
}

type BetaEventPayload struct {
	Note *string `+"`json:\"note,omitempty\"`"+`
}

type DeltaSSEPayload struct {
	Delta string `+"`json:\"delta\"`"+`
}

func DecodeRealtimePayload(eventType EventType, value any) (any, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encode %s payload: %w", eventType, err)
	}
	var payload any
	switch eventType {
	case EventAlphaEvent:
		payload = &AlphaEventPayload{}
	case EventBetaEvent:
		payload = &BetaEventPayload{}
	default:
		return nil, fmt.Errorf("unknown realtime event type %q", eventType)
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(payload); err != nil {
		return nil, fmt.Errorf("decode %s payload: %w", eventType, err)
	}
	return payload, nil
}
`, string(goSource))
	assert.Contains(t, string(goSource), "func DecodeRealtimePayload(eventType EventType, value any) (any, error)")
	assert.Equal(t, `// Code generated by genrealtime; DO NOT EDIT.

export const REALTIME_CONTRACT_VERSION = 1 as const

export type RealtimeEvent =
  | { type: 'alpha_event'; sequence: number; payload: { count: number; meta?: Record<string, unknown> } }
  | { type: 'beta_event'; sequence: number; payload: { note?: string | null } }

export type RealtimeSSEEvent =
  | { type: 'delta'; delta: string }

const websocketPayloads = {
  alpha_event: { count: 'number', meta: 'object?' },
  beta_event: { note: 'string|null?' },
} as const

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function matches(value: unknown, spec: string): boolean {
  const optional = spec.endsWith('?')
  const type = optional ? spec.slice(0, -1) : spec
  if (value === undefined) return optional
  if (type.endsWith('|null') && value === null) return true
  const base = type.replace('|null', '')
  if (base === 'object') return isObject(value)
  if (base === 'array') return Array.isArray(value)
  return typeof value === base
}

export function parseRealtimeEvent(value: unknown): RealtimeEvent | null {
  if (!isObject(value) || typeof value.type !== 'string' || typeof value.sequence !== 'number' || !isObject(value.payload)) return null
  const spec = websocketPayloads[value.type as keyof typeof websocketPayloads]
  if (!spec) return null
  for (const [name, type] of Object.entries(spec)) {
    if (!matches(value.payload[name], type)) return null
  }
  return value as RealtimeEvent
}
`, string(tsSource))
}

func TestGenerateRejectsInvalidContracts(t *testing.T) {
	tests := map[string]string{
		"duplicate names":        `{"version":1,"sse":[],"websocket":[{"name":"same","payload":{"properties":[]}},{"name":"same","payload":{"properties":[]}}]}`,
		"unsupported type":       `{"version":1,"sse":[],"websocket":[{"name":"event","payload":{"properties":[{"name":"x","type":"integer"}]}}]}`,
		"invalid identifier":     `{"version":1,"sse":[],"websocket":[{"name":"Not-Snake","payload":{"properties":[]}}]}`,
		"missing payload":        `{"version":1,"sse":[],"websocket":[{"name":"event"}]}`,
		"unknown contract field": `{"version":1,"sse":[],"websocket":[],"surprise":true}`,
	}
	for name, fixture := range tests {
		t.Run(name, func(t *testing.T) {
			_, _, err := Generate(strings.NewReader(fixture))
			require.Error(t, err)
		})
	}
}

func TestGoTypeUsesPointersForOptionalPrimitives(t *testing.T) {
	for _, property := range []propertySpec{
		{Name: "label", Type: "string"},
		{Name: "count", Type: "number"},
		{Name: "enabled", Type: "boolean"},
	} {
		require.True(t, strings.HasPrefix(goType(property), "*"), property.Name)
	}
	require.Equal(t, "int64", goType(propertySpec{Name: "count", Type: "number", Required: true}))
}
