package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

type contract struct {
	Version   int         `json:"version"`
	SSE       []eventSpec `json:"sse"`
	WebSocket []eventSpec `json:"websocket"`
}

type eventSpec struct {
	Name    string       `json:"name"`
	Payload *payloadSpec `json:"payload"`
}

type payloadSpec struct {
	Properties []propertySpec `json:"properties"`
}

type propertySpec struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	GoType   string `json:"go_type,omitempty"`
}

var identifierPattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`)

var supportedTypes = map[string]struct{}{
	"string": {}, "number": {}, "boolean": {}, "object": {}, "array": {},
	"string|null": {}, "number|null": {}, "boolean|null": {}, "object|null": {}, "array|null": {},
}

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"pascal": pascal,
	"goType": goType,
	"jsonTag": func(property propertySpec) string {
		if property.Required {
			return fmt.Sprintf("`json:\"%s\"`", property.Name)
		}
		return fmt.Sprintf("`json:\"%s,omitempty\"`", property.Name)
	},
}).Parse(`// Code generated by genrealtime; DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

const RealtimeContractVersion = {{.Version}}

type EventType string

// RealtimePtr preserves presence for optional primitive payload fields,
// including explicit zero and false values.
func RealtimePtr[T any](value T) *T { return &value }

type realtimeNumber interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~float32 | ~float64
}

func RealtimeInt64[T realtimeNumber](value T) *int64 {
	converted := int64(value)
	return &converted
}

func RealtimeFloat64[T realtimeNumber](value T) *float64 {
	converted := float64(value)
	return &converted
}

func RealtimeArray[T any](values []T) []any {
	result := make([]any, len(values))
	for index := range values {
		result[index] = values[index]
	}
	return result
}

func MustRealtimeObject(value any) map[string]any {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("encode realtime object: %v", err))
	}
	var result map[string]any
	if err := json.Unmarshal(encoded, &result); err != nil {
		panic(fmt.Sprintf("decode realtime object: %v", err))
	}
	return result
}

const (
{{- range .WebSocket}}
	Event{{pascal .Name}} EventType = "{{.Name}}"
{{- end}}
)

const (
{{- range .SSE}}
	SSEEvent{{pascal .Name}} = "{{.Name}}"
{{- end}}
)
{{range .WebSocket}}
type {{pascal .Name}}Payload struct {
{{- range .Payload.Properties}}
	{{pascal .Name}} {{goType .}} {{jsonTag .}}
{{- end}}
}
{{end}}{{range .SSE}}
type {{pascal .Name}}SSEPayload struct {
{{- range .Payload.Properties}}
	{{pascal .Name}} {{goType .}} {{jsonTag .}}
{{- end}}
}
{{end}}
func DecodeRealtimePayload(eventType EventType, value any) (any, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encode %s payload: %w", eventType, err)
	}
	var payload any
	switch eventType {
{{- range .WebSocket}}
	case Event{{pascal .Name}}:
		payload = &{{pascal .Name}}Payload{}
{{- end}}
	default:
		return nil, fmt.Errorf("unknown realtime event type %q", eventType)
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(payload); err != nil {
		return nil, fmt.Errorf("decode %s payload: %w", eventType, err)
	}
	return payload, nil
}
`))

var tsTemplate = template.Must(template.New("ts").Funcs(template.FuncMap{
	"pascal": pascal,
	"tsType": tsType,
	"optional": func(property propertySpec) string {
		if property.Required {
			return ""
		}
		return "?"
	},
	"runtimeType": func(property propertySpec) string {
		value := property.Type
		if !property.Required {
			value += "?"
		}
		return value
	},
}).Parse(`// Code generated by genrealtime; DO NOT EDIT.

export const REALTIME_CONTRACT_VERSION = {{.Version}} as const

export type RealtimeEvent =
{{- range .WebSocket}}
  | { type: '{{.Name}}'; sequence: number; payload: { {{range $index, $property := .Payload.Properties}}{{if $index}}; {{end}}{{$property.Name}}{{optional $property}}: {{tsType $property}}{{end}} } }
{{- end}}

export type RealtimeSSEEvent =
{{- range .SSE}}
  | { type: '{{.Name}}'{{range .Payload.Properties}}; {{.Name}}{{optional .}}: {{tsType .}}{{end}} }
{{- end}}

const websocketPayloads = {
{{- range .WebSocket}}
  {{.Name}}: { {{range $index, $property := .Payload.Properties}}{{if $index}}, {{end}}{{$property.Name}}: '{{runtimeType $property}}'{{end}} },
{{- end}}
} as const

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function matches(value: unknown, spec: string): boolean {
  const optional = spec.endsWith('?')
  const type = optional ? spec.slice(0, -1) : spec
  if (value === undefined) return optional
  if (type.endsWith('|null') && value === null) return true
  const base = type.replace('|null', '')
  if (base === 'object') return isObject(value)
  if (base === 'array') return Array.isArray(value)
  return typeof value === base
}

export function parseRealtimeEvent(value: unknown): RealtimeEvent | null {
  if (!isObject(value) || typeof value.type !== 'string' || typeof value.sequence !== 'number' || !isObject(value.payload)) return null
  const spec = websocketPayloads[value.type as keyof typeof websocketPayloads]
  if (!spec) return null
  for (const [name, type] of Object.entries(spec)) {
    if (!matches(value.payload[name], type)) return null
  }
  return value as RealtimeEvent
}
`))

func pascal(value string) string {
	parts := strings.Split(value, "_")
	for index, part := range parts {
		switch part {
		case "id", "npc", "xp", "fx", "sse":
			parts[index] = strings.ToUpper(part)
		default:
			parts[index] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func goType(property propertySpec) string {
	base := strings.TrimSuffix(property.Type, "|null")
	var value string
	switch base {
	case "string":
		value = "string"
	case "number":
		value = property.GoType
		if value == "" {
			value = "int64"
		}
	case "boolean":
		value = "bool"
	case "object":
		value = "map[string]any"
	case "array":
		value = "[]any"
	}
	primitive := base == "string" || base == "number" || base == "boolean"
	if primitive && (strings.HasSuffix(property.Type, "|null") || !property.Required) {
		value = "*" + value
	}
	return value
}

func tsType(property propertySpec) string {
	base := strings.TrimSuffix(property.Type, "|null")
	var value string
	switch base {
	case "string", "boolean":
		value = base
	case "number":
		value = "number"
	case "object":
		value = "Record<string, unknown>"
	case "array":
		value = "unknown[]"
	}
	if strings.HasSuffix(property.Type, "|null") {
		value += " | null"
	}
	return value
}

func validateEvents(kind string, events []eventSpec) error {
	seen := make(map[string]struct{}, len(events))
	for index := range events {
		event := &events[index]
		if !identifierPattern.MatchString(event.Name) {
			return fmt.Errorf("%s event %q is not snake_case", kind, event.Name)
		}
		if _, exists := seen[event.Name]; exists {
			return fmt.Errorf("duplicate %s event %q", kind, event.Name)
		}
		seen[event.Name] = struct{}{}
		if event.Payload == nil {
			return fmt.Errorf("%s event %q is missing payload", kind, event.Name)
		}
		propertyNames := make(map[string]struct{}, len(event.Payload.Properties))
		for _, property := range event.Payload.Properties {
			if !identifierPattern.MatchString(property.Name) {
				return fmt.Errorf("%s event %q property %q is not snake_case", kind, event.Name, property.Name)
			}
			if _, exists := propertyNames[property.Name]; exists {
				return fmt.Errorf("%s event %q has duplicate property %q", kind, event.Name, property.Name)
			}
			propertyNames[property.Name] = struct{}{}
			if _, supported := supportedTypes[property.Type]; !supported {
				return fmt.Errorf("%s event %q property %q has unsupported type %q", kind, event.Name, property.Name, property.Type)
			}
			if property.GoType != "" && (strings.TrimSuffix(property.Type, "|null") != "number" || (property.GoType != "int" && property.GoType != "int64" && property.GoType != "float64")) {
				return fmt.Errorf("%s event %q property %q has unsupported Go type %q", kind, event.Name, property.Name, property.GoType)
			}
		}
		sort.Slice(event.Payload.Properties, func(i, j int) bool {
			return event.Payload.Properties[i].Name < event.Payload.Properties[j].Name
		})
	}
	sort.Slice(events, func(i, j int) bool { return events[i].Name < events[j].Name })
	return nil
}

func Generate(reader io.Reader) ([]byte, []byte, error) {
	decoder := json.NewDecoder(reader)
	decoder.DisallowUnknownFields()
	var value contract
	if err := decoder.Decode(&value); err != nil {
		return nil, nil, fmt.Errorf("decode realtime contract: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, nil, errors.New("decode realtime contract: trailing JSON value")
	}
	if value.Version < 1 {
		return nil, nil, errors.New("realtime contract version must be positive")
	}
	if err := validateEvents("SSE", value.SSE); err != nil {
		return nil, nil, err
	}
	if err := validateEvents("WebSocket", value.WebSocket); err != nil {
		return nil, nil, err
	}

	var goBuffer bytes.Buffer
	if err := goTemplate.Execute(&goBuffer, value); err != nil {
		return nil, nil, fmt.Errorf("render Go realtime contract: %w", err)
	}
	goSource, err := format.Source(goBuffer.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("format Go realtime contract: %w", err)
	}
	var tsBuffer bytes.Buffer
	if err := tsTemplate.Execute(&tsBuffer, value); err != nil {
		return nil, nil, fmt.Errorf("render TypeScript realtime contract: %w", err)
	}
	return goSource, tsBuffer.Bytes(), nil
}

func writeIfDifferent(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func run() error {
	contractPath := flag.String("contract", "contracts/realtime.json", "canonical realtime contract")
	goPath := flag.String("go", "internal/api/realtime_gen.go", "generated Go output")
	tsPath := flag.String("ts", "web/src/realtime.gen.ts", "generated TypeScript output")
	flag.Parse()
	input, err := os.Open(*contractPath)
	if err != nil {
		return err
	}
	defer input.Close()
	goSource, tsSource, err := Generate(input)
	if err != nil {
		return err
	}
	if err := writeIfDifferent(*goPath, goSource); err != nil {
		return err
	}
	return writeIfDifferent(*tsPath, tsSource)
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
