version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - ST1000
    - ST1016
    - S1040
    - QF1012
