// Code generated by genrealtime; DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

const RealtimeContractVersion = 1

type EventType string

// RealtimePtr preserves presence for optional primitive payload fields,
// including explicit zero and false values.
func RealtimePtr[T any](value T) *T { return &value }

type realtimeNumber interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~float32 | ~float64
}

func RealtimeInt64[T realtimeNumber](value T) *int64 {
	converted := int64(value)
	return &converted
}

func RealtimeFloat64[T realtimeNumber](value T) *float64 {
	converted := float64(value)
	return &converted
}

func RealtimeArray[T any](values []T) []any {
	result := make([]any, len(values))
	for index := range values {
		result[index] = values[index]
	}
	return result
}

func MustRealtimeObject(value any) map[string]any {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("encode realtime object: %v", err))
	}
	var result map[string]any
	if err := json.Unmarshal(encoded, &result); err != nil {
		panic(fmt.Sprintf("decode realtime object: %v", err))
	}
	return result
}

const (
	EventAdventureUpdated      EventType = "adventure_updated"
	EventCalendarUpdated       EventType = "calendar_updated"
	EventCampaignClosed        EventType = "campaign_closed"
	EventCampaignConfigUpdated EventType = "campaign_config_updated"
	EventCampaignCreated       EventType = "campaign_created"
	EventCampaignDeleted       EventType = "campaign_deleted"
	EventCampaignReopened      EventType = "campaign_reopened"
	EventCampaignUpdated       EventType = "campaign_updated"
	EventCardDrawn             EventType = "card_drawn"
	EventCharacterCreated      EventType = "character_created"
	EventCharacterUpdated      EventType = "character_updated"
	EventCombatEnded           EventType = "combat_ended"
	EventCombatStarted         EventType = "combat_started"
	EventCombatantUpdated      EventType = "combatant_updated"
	EventContextUpdated        EventType = "context_updated"
	EventDiceRolled            EventType = "dice_rolled"
	EventExpectedAction        EventType = "expected_action"
	EventFactionUpdated        EventType = "faction_updated"
	EventItemUpdated           EventType = "item_updated"
	EventMapCreated            EventType = "map_created"
	EventMapFX                 EventType = "map_fx"
	EventMapPinAdded           EventType = "map_pin_added"
	EventMessageCreated        EventType = "message_created"
	EventNPCStatUpdated        EventType = "npc_stat_updated"
	EventNPCUpdated            EventType = "npc_updated"
	EventObjectiveUpdated      EventType = "objective_updated"
	EventOracleResult          EventType = "oracle_result"
	EventOracleRolled          EventType = "oracle_rolled"
	EventRelationshipUpdated   EventType = "relationship_updated"
	EventResyncRequired        EventType = "resync_required"
	EventSecretRevealed        EventType = "secret_revealed"
	EventSecretsUpdated        EventType = "secrets_updated"
	EventSessionDeleted        EventType = "session_deleted"
	EventSessionEnded          EventType = "session_ended"
	EventSessionStarted        EventType = "session_started"
	EventSessionUpdated        EventType = "session_updated"
	EventTensionUpdated        EventType = "tension_updated"
	EventTokenMoved            EventType = "token_moved"
	EventTokenPlaced           EventType = "token_placed"
	EventTokenRemoved          EventType = "token_removed"
	EventTurnAdvanced          EventType = "turn_advanced"
	EventTyping                EventType = "typing"
	EventWorldNoteCreated      EventType = "world_note_created"
	EventWorldNoteRevealed     EventType = "world_note_revealed"
	EventWorldNoteUpdated      EventType = "world_note_updated"
	EventXPAdded               EventType = "xp_added"
	EventXPSpendSuggestions    EventType = "xp_spend_suggestions"
	EventZoneRevealed          EventType = "zone_revealed"
)

const (
	SSEEventDelta = "delta"
	SSEEventDone  = "done"
	SSEEventError = "error"
)

type AdventureUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
	SessionID  *int64 `json:"session_id,omitempty"`
}

type CalendarUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
}

type CampaignClosedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
}

type CampaignConfigUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
}

type CampaignCreatedPayload struct {
	CampaignID *int64  `json:"campaign_id,omitempty"`
	Name       *string `json:"name,omitempty"`
}

type CampaignDeletedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
}

type CampaignReopenedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
}

type CampaignUpdatedPayload struct {
	CampaignID             *int64 `json:"campaign_id,omitempty"`
	ChronicleNight         *int64 `json:"chronicle_night,omitempty"`
	ChronicleNightStartDow *int64 `json:"chronicle_night_start_dow,omitempty"`
}

type CardDrawnPayload struct {
	CampaignID *int64         `json:"campaign_id,omitempty"`
	Card       map[string]any `json:"card,omitempty"`
	DeckID     *int64         `json:"deck_id,omitempty"`
	DeckName   *string        `json:"deck_name,omitempty"`
	DrawIndex  *int64         `json:"draw_index,omitempty"`
	SessionID  *int64         `json:"session_id,omitempty"`
	Total      *int64         `json:"total,omitempty"`
}

type CharacterCreatedPayload struct {
	CharacterID *int64  `json:"character_id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

type CharacterUpdatedPayload struct {
	CharacterID     *int64  `json:"character_id,omitempty"`
	Clan            *string `json:"clan,omitempty"`
	CurrencyBalance *int64  `json:"currency_balance,omitempty"`
	CurrencyDelta   *int64  `json:"currency_delta,omitempty"`
	CurrencyLabel   *string `json:"currency_label,omitempty"`
	DataJson        *string `json:"data_json,omitempty"`
	Embrace         *bool   `json:"embrace,omitempty"`
	Field           *string `json:"field,omitempty"`
	ID              *int64  `json:"id,omitempty"`
	NewValue        *int64  `json:"new_value,omitempty"`
	PortraitPath    *string `json:"portrait_path,omitempty"`
	PredatorType    *string `json:"predator_type,omitempty"`
	SessionID       *int64  `json:"session_id,omitempty"`
	XPCost          *int64  `json:"xp_cost,omitempty"`
}

type CombatEndedPayload struct {
	EncounterID *int64 `json:"encounter_id,omitempty"`
	SessionID   *int64 `json:"session_id,omitempty"`
}

type CombatStartedPayload struct {
	EncounterID *int64  `json:"encounter_id,omitempty"`
	Name        *string `json:"name,omitempty"`
	SessionID   *int64  `json:"session_id,omitempty"`
}

type CombatantUpdatedPayload struct {
	CombatantID *int64 `json:"combatant_id,omitempty"`
	EncounterID *int64 `json:"encounter_id,omitempty"`
	SessionID   *int64 `json:"session_id,omitempty"`
}

type ContextUpdatedPayload struct {
	CampaignID  *int64 `json:"campaign_id,omitempty"`
	CharacterID *int64 `json:"character_id,omitempty"`
	SessionID   *int64 `json:"session_id,omitempty"`
}

type DiceRolledPayload struct {
	BestialFail   *bool   `json:"bestial_fail,omitempty"`
	Breakdown     []any   `json:"breakdown,omitempty"`
	CharacterName *string `json:"character_name,omitempty"`
	Expression    *string `json:"expression,omitempty"`
	Hidden        *bool   `json:"hidden,omitempty"`
	HungerDice    []any   `json:"hunger_dice,omitempty"`
	MessyCritical *bool   `json:"messy_critical,omitempty"`
	NormalDice    []any   `json:"normal_dice,omitempty"`
	Result        *int64  `json:"result,omitempty"`
	Rolls         []any   `json:"rolls,omitempty"`
	SessionID     *int64  `json:"session_id,omitempty"`
	Successes     *int64  `json:"successes,omitempty"`
}

type ExpectedActionPayload struct {
	CharacterID   *int64  `json:"character_id,omitempty"`
	CharacterName *string `json:"character_name,omitempty"`
	SessionID     *int64  `json:"session_id,omitempty"`
}

type FactionUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
}

type ItemUpdatedPayload struct {
	CharacterID *int64 `json:"character_id,omitempty"`
	ItemID      *int64 `json:"item_id,omitempty"`
}

type MapCreatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	MapID      *int64 `json:"map_id,omitempty"`
}

type MapFXPayload struct {
	DurationMs *int64   `json:"duration_ms,omitempty"`
	Effect     *string  `json:"effect,omitempty"`
	MapID      *int64   `json:"map_id,omitempty"`
	X          *float64 `json:"x,omitempty"`
	Y          *float64 `json:"y,omitempty"`
}

type MapPinAddedPayload struct {
	Label *string `json:"label,omitempty"`
	MapID *int64  `json:"map_id,omitempty"`
	PinID *int64  `json:"pin_id,omitempty"`
}

type MessageCreatedPayload struct {
	CharacterID *int64  `json:"character_id,omitempty"`
	Content     *string `json:"content,omitempty"`
	MessageID   *int64  `json:"message_id,omitempty"`
	Role        *string `json:"role,omitempty"`
	SessionID   *int64  `json:"session_id,omitempty"`
}

type NPCStatUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
}

type NPCUpdatedPayload struct {
	NPCID     *int64 `json:"npc_id,omitempty"`
	SessionID *int64 `json:"session_id,omitempty"`
}

type ObjectiveUpdatedPayload struct {
	CampaignID  *int64 `json:"campaign_id,omitempty"`
	ObjectiveID *int64 `json:"objective_id,omitempty"`
}

type OracleResultPayload struct {
	IsCompulsion *bool   `json:"is_compulsion,omitempty"`
	Result       *string `json:"result,omitempty"`
	Roll         *int64  `json:"roll,omitempty"`
	SessionID    *int64  `json:"session_id,omitempty"`
	Table        *string `json:"table,omitempty"`
}

type OracleRolledPayload struct {
	Result    *string `json:"result,omitempty"`
	Roll      *int64  `json:"roll,omitempty"`
	SessionID *int64  `json:"session_id,omitempty"`
	Table     *string `json:"table,omitempty"`
}

type RelationshipUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
}

type ResyncRequiredPayload struct {
	FromSequence int64 `json:"from_sequence"`
	ToSequence   int64 `json:"to_sequence"`
}

type SecretRevealedPayload struct {
	CampaignID *int64  `json:"campaign_id,omitempty"`
	Category   *string `json:"category,omitempty"`
	Content    *string `json:"content,omitempty"`
	ID         *int64  `json:"id,omitempty"`
	SessionID  *int64  `json:"session_id,omitempty"`
	Title      *string `json:"title,omitempty"`
}

type SecretsUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
}

type SessionDeletedPayload struct {
	SessionID *int64 `json:"session_id,omitempty"`
}

type SessionEndedPayload struct {
	SessionID *int64 `json:"session_id,omitempty"`
}

type SessionStartedPayload struct {
	SessionID *int64  `json:"session_id,omitempty"`
	Title     *string `json:"title,omitempty"`
}

type SessionUpdatedPayload struct {
	AdventureID         *int64  `json:"adventure_id,omitempty"`
	CampaignID          *int64  `json:"campaign_id,omitempty"`
	MasqueradeIntegrity *int64  `json:"masquerade_integrity,omitempty"`
	Notes               *string `json:"notes,omitempty"`
	SceneTags           *string `json:"scene_tags,omitempty"`
	SessionID           *int64  `json:"session_id,omitempty"`
	Summary             *string `json:"summary,omitempty"`
}

type TensionUpdatedPayload struct {
	SessionID    *int64 `json:"session_id,omitempty"`
	TensionLevel *int64 `json:"tension_level,omitempty"`
}

type TokenMovedPayload struct {
	MapID   *int64   `json:"map_id,omitempty"`
	TokenID *int64   `json:"token_id,omitempty"`
	X       *float64 `json:"x,omitempty"`
	Y       *float64 `json:"y,omitempty"`
}

type TokenPlacedPayload struct {
	MapID *int64         `json:"map_id,omitempty"`
	Token map[string]any `json:"token,omitempty"`
}

type TokenRemovedPayload struct {
	MapID   *int64 `json:"map_id,omitempty"`
	TokenID *int64 `json:"token_id,omitempty"`
}

type TurnAdvancedPayload struct {
	ActiveTurnIndex *int64 `json:"active_turn_index,omitempty"`
	EncounterID     *int64 `json:"encounter_id,omitempty"`
	RoundNumber     *int64 `json:"round_number,omitempty"`
	SessionID       *int64 `json:"session_id,omitempty"`
}

type TypingPayload struct {
	CharacterID   *int64  `json:"character_id,omitempty"`
	CharacterName *string `json:"character_name,omitempty"`
	SessionID     *int64  `json:"session_id,omitempty"`
	Status        *string `json:"status,omitempty"`
}

type WorldNoteCreatedPayload struct {
	CampaignID *int64  `json:"campaign_id,omitempty"`
	NoteID     *int64  `json:"note_id,omitempty"`
	Title      *string `json:"title,omitempty"`
}

type WorldNoteRevealedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	ID         *int64 `json:"id,omitempty"`
	IsRevealed *bool  `json:"is_revealed,omitempty"`
	NoteID     *int64 `json:"note_id,omitempty"`
	SessionID  *int64 `json:"session_id,omitempty"`
}

type WorldNoteUpdatedPayload struct {
	CampaignID *int64 `json:"campaign_id,omitempty"`
	NoteID     *int64 `json:"note_id,omitempty"`
}

type XPAddedPayload struct {
	Amount    *int    `json:"amount,omitempty"`
	ID        *int64  `json:"id,omitempty"`
	Note      *string `json:"note,omitempty"`
	SessionID *int64  `json:"session_id,omitempty"`
}

type XPSpendSuggestionsPayload struct {
	CharacterID   *int64  `json:"character_id,omitempty"`
	CharacterName *string `json:"character_name,omitempty"`
	CurrentXP     *int64  `json:"current_xp,omitempty"`
	SessionID     *int64  `json:"session_id,omitempty"`
	Suggestions   []any   `json:"suggestions,omitempty"`
	XPLabel       *string `json:"xp_label,omitempty"`
}

type ZoneRevealedPayload struct {
	IsRevealed *bool   `json:"is_revealed,omitempty"`
	MapID      *int64  `json:"map_id,omitempty"`
	ZoneID     *int64  `json:"zone_id,omitempty"`
	ZoneName   *string `json:"zone_name,omitempty"`
}

type DeltaSSEPayload struct {
	Delta string `json:"delta"`
}

type DoneSSEPayload struct {
}

type ErrorSSEPayload struct {
	Code      string `json:"code"`
	RequestID string `json:"request_id"`
}

func DecodeRealtimePayload(eventType EventType, value any) (any, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encode %s payload: %w", eventType, err)
	}
	var payload any
	switch eventType {
	case EventAdventureUpdated:
		payload = &AdventureUpdatedPayload{}
	case EventCalendarUpdated:
		payload = &CalendarUpdatedPayload{}
	case EventCampaignClosed:
		payload = &CampaignClosedPayload{}
	case EventCampaignConfigUpdated:
		payload = &CampaignConfigUpdatedPayload{}
	case EventCampaignCreated:
		payload = &CampaignCreatedPayload{}
	case EventCampaignDeleted:
		payload = &CampaignDeletedPayload{}
	case EventCampaignReopened:
		payload = &CampaignReopenedPayload{}
	case EventCampaignUpdated:
		payload = &CampaignUpdatedPayload{}
	case EventCardDrawn:
		payload = &CardDrawnPayload{}
	case EventCharacterCreated:
		payload = &CharacterCreatedPayload{}
	case EventCharacterUpdated:
		payload = &CharacterUpdatedPayload{}
	case EventCombatEnded:
		payload = &CombatEndedPayload{}
	case EventCombatStarted:
		payload = &CombatStartedPayload{}
	case EventCombatantUpdated:
		payload = &CombatantUpdatedPayload{}
	case EventContextUpdated:
		payload = &ContextUpdatedPayload{}
	case EventDiceRolled:
		payload = &DiceRolledPayload{}
	case EventExpectedAction:
		payload = &ExpectedActionPayload{}
	case EventFactionUpdated:
		payload = &FactionUpdatedPayload{}
	case EventItemUpdated:
		payload = &ItemUpdatedPayload{}
	case EventMapCreated:
		payload = &MapCreatedPayload{}
	case EventMapFX:
		payload = &MapFXPayload{}
	case EventMapPinAdded:
		payload = &MapPinAddedPayload{}
	case EventMessageCreated:
		payload = &MessageCreatedPayload{}
	case EventNPCStatUpdated:
		payload = &NPCStatUpdatedPayload{}
	case EventNPCUpdated:
		payload = &NPCUpdatedPayload{}
	case EventObjectiveUpdated:
		payload = &ObjectiveUpdatedPayload{}
	case EventOracleResult:
		payload = &OracleResultPayload{}
	case EventOracleRolled:
		payload = &OracleRolledPayload{}
	case EventRelationshipUpdated:
		payload = &RelationshipUpdatedPayload{}
	case EventResyncRequired:
		payload = &ResyncRequiredPayload{}
	case EventSecretRevealed:
		payload = &SecretRevealedPayload{}
	case EventSecretsUpdated:
		payload = &SecretsUpdatedPayload{}
	case EventSessionDeleted:
		payload = &SessionDeletedPayload{}
	case EventSessionEnded:
		payload = &SessionEndedPayload{}
	case EventSessionStarted:
		payload = &SessionStartedPayload{}
	case EventSessionUpdated:
		payload = &SessionUpdatedPayload{}
	case EventTensionUpdated:
		payload = &TensionUpdatedPayload{}
	case EventTokenMoved:
		payload = &TokenMovedPayload{}
	case EventTokenPlaced:
		payload = &TokenPlacedPayload{}
	case EventTokenRemoved:
		payload = &TokenRemovedPayload{}
	case EventTurnAdvanced:
		payload = &TurnAdvancedPayload{}
	case EventTyping:
		payload = &TypingPayload{}
	case EventWorldNoteCreated:
		payload = &WorldNoteCreatedPayload{}
	case EventWorldNoteRevealed:
		payload = &WorldNoteRevealedPayload{}
	case EventWorldNoteUpdated:
		payload = &WorldNoteUpdatedPayload{}
	case EventXPAdded:
		payload = &XPAddedPayload{}
	case EventXPSpendSuggestions:
		payload = &XPSpendSuggestionsPayload{}
	case EventZoneRevealed:
		payload = &ZoneRevealedPayload{}
	default:
		return nil, fmt.Errorf("unknown realtime event type %q", eventType)
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(payload); err != nil {
		return nil, fmt.Errorf("decode %s payload: %w", eventType, err)
	}
	return payload, nil
}
