-- 040_schema_min_max_options.sql
-- Adds min/max for attribute pips and track bars, options for dropdown fields,
-- and default values to all 14 ruleset schemas.

-- 1. dnd5e
UPDATE rulesets SET schema_json = '[
  {"key":"race","label":"Race","type":"text","category":"identity","options":["Dragonborn","Dwarf","Elf","Gnome","Half-Elf","Half-Orc","Halfling","Human","Tiefling","Aasimar","Firbolg","Goliath","Kenku","Lizardfolk","Tabaxi","Triton","Yuan-ti Pureblood"],"default":"Human"},
  {"key":"class","label":"Class","type":"text","category":"identity","options":["Barbarian","Bard","Cleric","Druid","Fighter","Monk","Paladin","Ranger","Rogue","Sorcerer","Warlock","Wizard","Artificer","Blood Hunter"],"default":"Fighter"},
  {"key":"level","label":"Level","type":"number","category":"resource","min":1,"max":20,"default":"1"},
  {"key":"hp","label":"HP","type":"number","category":"track","max":999},
  {"key":"ac","label":"AC","type":"number","category":"resource","min":0,"max":30,"default":"10"},
  {"key":"str","label":"STR","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"dex","label":"DEX","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"con","label":"CON","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"int","label":"INT","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"wis","label":"WIS","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"cha","label":"CHA","type":"number","category":"attribute","min":1,"max":30,"default":"10"},
  {"key":"proficiency_bonus","label":"Proficiency Bonus","type":"number","category":"resource","min":2,"max":9,"default":"2"},
  {"key":"skills","label":"Skills","type":"textarea","category":"notes"},
  {"key":"inventory","label":"Inventory","type":"textarea","category":"notes"},
  {"key":"spells","label":"Spells","type":"textarea","category":"notes"},
  {"key":"features","label":"Features","type":"textarea","category":"notes"}
]' WHERE name = 'dnd5e';

-- 2. ironsworn
UPDATE rulesets SET schema_json = '[
  {"key":"edge","label":"Edge","type":"number","category":"attribute","min":1,"max":3,"default":"2"},
  {"key":"heart","label":"Heart","type":"number","category":"attribute","min":1,"max":3,"default":"2"},
  {"key":"iron","label":"Iron","type":"number","category":"attribute","min":1,"max":3,"default":"2"},
  {"key":"shadow","label":"Shadow","type":"number","category":"attribute","min":1,"max":3,"default":"2"},
  {"key":"wits","label":"Wits","type":"number","category":"attribute","min":1,"max":3,"default":"2"},
  {"key":"health","label":"Health","type":"number","category":"track","max":5,"default":"5"},
  {"key":"spirit","label":"Spirit","type":"number","category":"track","max":5,"default":"5"},
  {"key":"supply","label":"Supply","type":"number","category":"track","max":5,"default":"5"},
  {"key":"momentum","label":"Momentum","type":"number","category":"track","max":10,"default":"2"},
  {"key":"vows","label":"Vows","type":"textarea","category":"notes"},
  {"key":"bonds","label":"Bonds","type":"textarea","category":"notes"},
  {"key":"assets","label":"Assets","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'ironsworn';

-- 3. vtm
UPDATE rulesets SET schema_json = '[
  {"key":"character_type","label":"Character Type","type":"text","category":"identity","options":["Vampire","Thin-Blooded","Ghoul","Mortal"],"default":"Vampire"},
  {"key":"clan","label":"Clan","type":"text","category":"identity","options":["Brujah","Gangrel","Malkavian","Nosferatu","Toreador","Tremere","Ventrue","Caitiff","Thin-Blooded","Banu Haqim","Hecata","Lasombra","Ministry","Ravnos","Salubri","Tzimisce"]},
  {"key":"predator_type","label":"Predator Type","type":"text","category":"identity","options":["Alleycat","Bagger","Blood Leech","Cleaner","Consensualist","Extortionist","Graverobber","Osiris","Sandman","Siren","Farmer","Montero","Scene Queen","Treasure Hunter","Pursuer","Witch Hunter"]},
  {"key":"sect","label":"Sect","type":"text","category":"identity","options":["Camarilla","Anarch","Unaligned","Sabbat (lapsed)"]},
  {"key":"generation","label":"Generation","type":"text","category":"identity","options":["10th","11th","12th","13th","14th","15th (Thin-Blooded)","16th (Thin-Blooded)"],"default":"13th"},
  {"key":"hunger","label":"Hunger","type":"number","category":"resource","min":0,"max":5,"default":"1"},
  {"key":"blood_potency","label":"Blood Potency","type":"number","category":"resource","min":0,"max":10,"default":"1"},
  {"key":"bane_severity","label":"Bane Severity","type":"number","category":"resource","min":0,"max":3,"default":"1"},
  {"key":"humanity","label":"Humanity","type":"number","category":"resource","min":0,"max":10,"default":"7"},
  {"key":"stains","label":"Stains","type":"number","category":"resource","min":0,"max":10,"default":"0"},
  {"key":"strength","label":"Strength","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"dexterity","label":"Dexterity","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"stamina","label":"Stamina","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"charisma","label":"Charisma","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"manipulation","label":"Manipulation","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"composure","label":"Composure","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"intelligence","label":"Intelligence","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"wits","label":"Wits","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"resolve","label":"Resolve","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"athletics","label":"Athletics","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"brawl","label":"Brawl","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"craft","label":"Craft","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"drive","label":"Drive","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"firearms","label":"Firearms","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"larceny","label":"Larceny","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"melee","label":"Melee","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"stealth","label":"Stealth","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"survival","label":"Survival","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"animal_ken","label":"Animal Ken","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"etiquette","label":"Etiquette","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"insight","label":"Insight","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"intimidation","label":"Intimidation","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"leadership","label":"Leadership","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"performance","label":"Performance","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"persuasion","label":"Persuasion","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"streetwise","label":"Streetwise","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"subterfuge","label":"Subterfuge","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"academics","label":"Academics","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"awareness","label":"Awareness","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"finance","label":"Finance","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"investigation","label":"Investigation","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"medicine","label":"Medicine","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"occult","label":"Occult","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"politics","label":"Politics","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"technology","label":"Technology","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"animalism","label":"Animalism","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"auspex","label":"Auspex","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"blood_sorcery","label":"Blood Sorcery","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"celerity","label":"Celerity","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"dominate","label":"Dominate","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"fortitude","label":"Fortitude","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"obfuscate","label":"Obfuscate","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"oblivion","label":"Oblivion","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"potence","label":"Potence","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"presence","label":"Presence","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"protean","label":"Protean","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"thin_blood_alchemy","label":"Thin-Blood Alchemy","type":"number","category":"skill","min":0,"max":5,"default":"0"},
  {"key":"health_max","label":"Health Max","type":"number","category":"resource","min":1,"max":20,"default":"6"},
  {"key":"health_superficial","label":"Health Superficial","type":"number","category":"resource","min":0,"max":20,"default":"0"},
  {"key":"health_aggravated","label":"Health Aggravated","type":"number","category":"resource","min":0,"max":20,"default":"0"},
  {"key":"willpower_max","label":"Willpower Max","type":"number","category":"resource","min":1,"max":20,"default":"6"},
  {"key":"willpower_superficial","label":"Willpower Superficial","type":"number","category":"resource","min":0,"max":20,"default":"0"},
  {"key":"willpower_aggravated","label":"Willpower Aggravated","type":"number","category":"resource","min":0,"max":20,"default":"0"},
  {"key":"domitor","label":"Domitor","type":"text","category":"identity"},
  {"key":"bond_strength","label":"Bond Strength","type":"number","category":"resource","min":0,"max":3,"default":"0"},
  {"key":"skill_specialties","label":"Skill Specialties","type":"textarea","category":"notes"},
  {"key":"merits_flaws","label":"Merits & Flaws","type":"textarea","category":"notes"},
  {"key":"convictions","label":"Convictions","type":"textarea","category":"notes"},
  {"key":"touchstones","label":"Touchstones","type":"textarea","category":"notes"},
  {"key":"ambition","label":"Ambition","type":"text","category":"identity"},
  {"key":"desire","label":"Desire","type":"text","category":"identity"},
  {"key":"rituals","label":"Rituals","type":"textarea","category":"notes"},
  {"key":"ceremonies","label":"Ceremonies","type":"textarea","category":"notes"},
  {"key":"known_formulae","label":"Known Formulae","type":"textarea","category":"notes"},
  {"key":"loresheets","label":"Loresheets","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"},
  {"key":"xp","label":"XP","type":"number","category":"resource","min":0,"max":999,"default":"0"}
]' WHERE name = 'vtm';

-- 4. coc
UPDATE rulesets SET schema_json = '[
  {"key":"occupation","label":"Occupation","type":"text","category":"identity","options":["Antiquarian","Artist","Author","Detective","Doctor","Engineer","Journalist","Military Officer","Occultist","Parapsychologist","Police Inspector","Professor","Thief"]},
  {"key":"age","label":"Age","type":"number","category":"resource","min":15,"max":99,"default":"25"},
  {"key":"hp","label":"HP","type":"number","category":"track","max":99},
  {"key":"sanity","label":"Sanity","type":"number","category":"track","max":99},
  {"key":"luck","label":"Luck","type":"number","category":"resource","min":0,"max":100,"default":"50"},
  {"key":"mp","label":"MP","type":"number","category":"resource","min":0,"max":99,"default":"10"},
  {"key":"str","label":"STR","type":"number","category":"attribute","min":3,"max":"18","default":"10"},
  {"key":"con","label":"CON","type":"number","category":"attribute","min":3,"max":18,"default":"10"},
  {"key":"siz","label":"SIZ","type":"number","category":"attribute","min":6,"max":24,"default":"12"},
  {"key":"dex","label":"DEX","type":"number","category":"attribute","min":3,"max":18,"default":"10"},
  {"key":"app","label":"APP","type":"number","category":"attribute","min":3,"max":18,"default":"10"},
  {"key":"int","label":"INT","type":"number","category":"attribute","min":6,"max":24,"default":"12"},
  {"key":"pow","label":"POW","type":"number","category":"attribute","min":3,"max":18,"default":"10"},
  {"key":"edu","label":"EDU","type":"number","category":"attribute","min":6,"max":24,"default":"12"},
  {"key":"skills","label":"Skills","type":"textarea","category":"notes"},
  {"key":"inventory","label":"Inventory","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'coc';

-- 5. cyberpunk
UPDATE rulesets SET schema_json = '[
  {"key":"role","label":"Role","type":"text","category":"identity","options":["Rockerboy","Solo","Netrunner","Tech","Medtech","Media","Cop","Corporate","Fixer","Nomad"]},
  {"key":"int","label":"INT","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"ref","label":"REF","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"cool","label":"COOL","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"tech","label":"TECH","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"lk","label":"LK","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"att","label":"ATT","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"ma","label":"MA","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"emp","label":"EMP","type":"number","category":"attribute","min":0,"max":10,"default":"6"},
  {"key":"body","label":"BODY","type":"number","category":"attribute","min":2,"max":10,"default":"6"},
  {"key":"humanity","label":"Humanity","type":"number","category":"resource","min":0,"max":99,"default":"60"},
  {"key":"eurodollars","label":"Eurodollars","type":"number","category":"resource","min":0,"max":99999,"default":"500"},
  {"key":"skills","label":"Skills","type":"textarea","category":"notes"},
  {"key":"cyberware","label":"Cyberware","type":"textarea","category":"notes"},
  {"key":"gear","label":"Gear","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'cyberpunk';

-- 6. shadowrun
UPDATE rulesets SET schema_json = '[
  {"key":"metatype","label":"Metatype","type":"text","category":"identity","options":["Human","Elf","Dwarf","Ork","Troll"],"default":"Human"},
  {"key":"priority","label":"Priority","type":"text","category":"identity","options":["A/B/C/D/E"]},
  {"key":"body","label":"Body","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"agility","label":"Agility","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"reaction","label":"Reaction","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"strength","label":"Strength","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"willpower","label":"Willpower","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"logic","label":"Logic","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"intuition","label":"Intuition","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"charisma","label":"Charisma","type":"number","category":"attribute","min":1,"max":10,"default":"3"},
  {"key":"edge","label":"Edge","type":"number","category":"resource","min":1,"max":10,"default":"2"},
  {"key":"essence","label":"Essence","type":"number","category":"resource","min":0,"max":6,"default":"6"},
  {"key":"physical_limit","label":"Phys Limit","type":"number","category":"resource","min":0,"max":20,"default":"5"},
  {"key":"mental_limit","label":"Mental Limit","type":"number","category":"resource","min":0,"max":20,"default":"5"},
  {"key":"social_limit","label":"Social Limit","type":"number","category":"resource","min":0,"max":20,"default":"5"},
  {"key":"nuyen","label":"Nuyen","type":"number","category":"resource","min":0,"max":999999,"default":"500"},
  {"key":"karma","label":"Karma","type":"number","category":"resource","min":0,"max":999,"default":"0"},
  {"key":"reputation","label":"Reputation","type":"number","category":"resource","min":0,"max":"99","default":"0"},
  {"key":"notoriety","label":"Notoriety","type":"number","category":"resource","min":0,"max":"99","default":"0"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'shadowrun';

-- 7. wfrp
UPDATE rulesets SET schema_json = '[
  {"key":"species","label":"Species","type":"text","category":"identity","options":["Human","Halfling","Dwarf","High Elf","Wood Elf"]},
  {"key":"career","label":"Career","type":"text","category":"identity","options":["Apothecary","Engineer","Lawyer","Physician","Scholar","Wizard","Agitator","Artisan","Beggar","Investigator","Merchant","Rat Catcher","Soldier","Thief","Entertainer","Messenger","Scout"]},
  {"key":"career_level","label":"Career Level","type":"number","category":"resource","min":1,"max":4,"default":"1"},
  {"key":"ws","label":"WS","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"bs","label":"BS","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"s","label":"S","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"t","label":"T","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"ag","label":"Ag","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"i","label":"I","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"dex","label":"Dex","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"int","label":"Int","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"wp","label":"WP","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"fel","label":"Fel","type":"number","category":"attribute","min":10,"max":50,"default":"28"},
  {"key":"wounds","label":"Wounds","type":"number","category":"track","max":30,"default":"10"},
  {"key":"fate","label":"Fate","type":"number","category":"resource","min":0,"max":6,"default":"2"},
  {"key":"fortune","label":"Fortune","type":"number","category":"resource","min":0,"max":6,"default":"2"},
  {"key":"resilience","label":"Resilience","type":"number","category":"resource","min":0,"max":6,"default":"1"},
  {"key":"resolve","label":"Resolve","type":"number","category":"resource","min":0,"max":6,"default":"1"},
  {"key":"xp","label":"XP","type":"number","category":"resource","min":0,"max":99999,"default":"0"},
  {"key":"ambitions","label":"Ambitions","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'wfrp';

-- 8. starwars
UPDATE rulesets SET schema_json = '[
  {"key":"species","label":"Species","type":"text","category":"identity","options":["Human","Twi''lek","Rodian","Wookiee","Bothan","Mon Calamari","Trandoshan","Duros","Zabrak","Togruta"]},
  {"key":"career","label":"Career","type":"text","category":"identity","options":["Bounty Hunter","Colonist","Explorer","Hired Gun","Mystic","Smuggler","Technician"]},
  {"key":"specialization","label":"Specialization","type":"text","category":"identity"},
  {"key":"brawn","label":"Brawn","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"agility","label":"Agility","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"intellect","label":"Intellect","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"cunning","label":"Cunning","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"willpower","label":"Willpower","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"presence","label":"Presence","type":"number","category":"attribute","min":1,"max":6,"default":"2"},
  {"key":"wounds_threshold","label":"Wounds Max","type":"number","category":"track","max":30,"default":"12"},
  {"key":"wounds_current","label":"Wounds","type":"number","category":"track","max":30,"default":"0"},
  {"key":"strain_threshold","label":"Strain Max","type":"number","category":"track","max":30,"default":"12"},
  {"key":"strain_current","label":"Strain","type":"number","category":"track","max":30,"default":"0"},
  {"key":"soak","label":"Soak","type":"number","category":"resource","min":0,"max":20,"default":"2"},
  {"key":"defense_melee","label":"Def Melee","type":"number","category":"resource","min":0,"max":"10","default":"0"},
  {"key":"defense_ranged","label":"Def Ranged","type":"number","category":"resource","min":0,"max":"10","default":"0"},
  {"key":"obligation","label":"Obligation","type":"number","category":"resource","min":0,"max":100,"default":"15"},
  {"key":"credits","label":"Credits","type":"number","category":"resource","min":0,"max":999999,"default":"500"},
  {"key":"force_rating","label":"Force Rating","type":"number","category":"resource","min":0,"max":10,"default":"0"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'starwars';

-- 9. l5r
UPDATE rulesets SET schema_json = '[
  {"key":"clan","label":"Clan","type":"text","category":"identity","options":["Crab","Crane","Dragon","Lion","Mantis","Phoenix","Scorpion","Unicorn"]},
  {"key":"family","label":"Family","type":"text","category":"identity"},
  {"key":"school","label":"School","type":"text","category":"identity"},
  {"key":"school_rank","label":"School Rank","type":"number","category":"resource","min":1,"max":5,"default":"1"},
  {"key":"air","label":"Air","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"earth","label":"Earth","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"fire","label":"Fire","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"water","label":"Water","type":"number","category":"attribute","min":1,"max":5,"default":"2"},
  {"key":"void","label":"Void","type":"number","category":"attribute","min":1,"max":5,"default":"1"},
  {"key":"endurance","label":"Endurance","type":"number","category":"track","max":20,"default":"8"},
  {"key":"composure","label":"Composure","type":"number","category":"track","max":20,"default":"8"},
  {"key":"focus","label":"Focus","type":"number","category":"resource","min":1,"max":10,"default":"3"},
  {"key":"vigilance","label":"Vigilance","type":"number","category":"resource","min":1,"max":10,"default":"2"},
  {"key":"glory","label":"Glory","type":"number","category":"resource","min":0,"max":100,"default":"45"},
  {"key":"honor","label":"Honor","type":"number","category":"resource","min":0,"max":100,"default":"45"},
  {"key":"status","label":"Status","type":"number","category":"resource","min":0,"max":100,"default":"30"},
  {"key":"xp","label":"XP","type":"number","category":"resource","min":0,"max":9999,"default":"0"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'l5r';

-- 10. theonering
UPDATE rulesets SET schema_json = '[
  {"key":"culture","label":"Culture","type":"text","category":"identity","options":["Bardings","Beornings","Dwarves of Erebor","Elves of Mirkwood","Hobbits of the Shire","Men of Bree","Rangers of the North","Woodmen of Wilderland"]},
  {"key":"calling","label":"Calling","type":"text","category":"identity","options":["Scholar","Slayer","Treasure Hunter","Wanderer","Warden"]},
  {"key":"body","label":"Body","type":"number","category":"attribute","min":1,"max":10,"default":"4"},
  {"key":"heart","label":"Heart","type":"number","category":"attribute","min":1,"max":10,"default":"4"},
  {"key":"wits","label":"Wits","type":"number","category":"attribute","min":1,"max":10,"default":"4"},
  {"key":"endurance","label":"Endurance","type":"number","category":"track","max":40,"default":"24"},
  {"key":"endurance_max","label":"Endurance Max","type":"number","category":"track","max":40,"default":"24"},
  {"key":"hope","label":"Hope","type":"number","category":"track","max":20,"default":"12"},
  {"key":"hope_max","label":"Hope Max","type":"number","category":"track","max":20,"default":"12"},
  {"key":"shadow_points","label":"Shadow Pts","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"shadow_scars","label":"Shadow Scars","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"valour","label":"Valour","type":"number","category":"resource","min":0,"max":10,"default":"1"},
  {"key":"wisdom","label":"Wisdom","type":"number","category":"resource","min":0,"max":10,"default":"1"},
  {"key":"standing","label":"Standing","type":"text","category":"identity","options":["Emissary","Exile","Honoured","Renowned","Strider"]},
  {"key":"fellowship_score","label":"Fellowship","type":"number","category":"resource","min":0,"max":30,"default":"18"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'theonering';

-- 11. wrath_glory
UPDATE rulesets SET schema_json = '[
  {"key":"archetype","label":"Archetype","type":"text","category":"identity","options":["Sister Hospitaller","Ministorum Priest","Imperial Guardsman","Inquisitorial Acolyte","Inquisitorial Sage","Ganger","Corsair","Boy","Cultist","Sister of Battle","Sanctioned Psyker","Skitarius","Death Cult Assassin","Tempestus Scion","Rogue Trader","Scavvy","Space Marine Scout","Ranger","Kommando","Rogue Psyker","Tech-Priest","Crusader","Imperial Commissar","Desperado","Tactical Space Marine","Warlock","Nob","Heretek","Chaos Space Marine","Inquisitor","Primaris Intercessor"]},
  {"key":"faction","label":"Faction","type":"text","category":"identity","options":["Adepta Sororitas","Adeptus Ministorum","Astra Militarum","Inquisition","Underhive","Rogue Traders","Orks","Chaos Undivided","Adeptus Mechanicus","Officio Assassinorum","Aeldari","Adeptus Astartes","Chaos Undivided"]},
  {"key":"rank","label":"Rank","type":"number","category":"resource","min":1,"max":4,"default":"1"},
  {"key":"keywords","label":"Keywords","type":"text","category":"identity"},
  {"key":"strength","label":"Strength","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"agility","label":"Agility","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"toughness","label":"Toughness","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"intellect","label":"Intellect","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"willpower","label":"Willpower","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"fellowship","label":"Fellowship","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"initiative","label":"Initiative","type":"number","category":"attribute","min":1,"max":12,"default":"3"},
  {"key":"ws","label":"Weapon Skill","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"bs","label":"Ballistic Skill","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"athletics","label":"Athletics","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"awareness","label":"Awareness","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"cunning","label":"Cunning","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"deception","label":"Deception","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"fortitude","label":"Fortitude","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"insight","label":"Insight","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"intimidation","label":"Intimidation","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"investigation","label":"Investigation","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"leadership","label":"Leadership","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"medicae","label":"Medicae","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"persuasion","label":"Persuasion","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"pilot","label":"Pilot","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"psychic_mastery","label":"Psychic Mastery","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"scholar","label":"Scholar","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"stealth","label":"Stealth","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"survival","label":"Survival","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"tech","label":"Tech","type":"number","category":"skill","min":0,"max":10,"default":"0"},
  {"key":"speed","label":"Speed","type":"number","category":"resource","min":1,"max":12,"default":"6"},
  {"key":"defence","label":"Defence","type":"number","category":"resource","min":0,"max":20,"default":"3"},
  {"key":"resilience","label":"Resilience","type":"number","category":"resource","min":0,"max":20,"default":"4"},
  {"key":"determination","label":"Determination","type":"number","category":"resource","min":0,"max":"20","default":"3"},
  {"key":"resolve","label":"Resolve","type":"number","category":"resource","min":0,"max":"20","default":"3"},
  {"key":"conviction","label":"Conviction","type":"number","category":"resource","min":0,"max":"20","default":"3"},
  {"key":"influence","label":"Influence","type":"number","category":"resource","min":0,"max":"20","default":"3"},
  {"key":"wounds","label":"Wounds","type":"number","category":"track","max":40,"default":"10"},
  {"key":"shock","label":"Shock","type":"number","category":"track","max":30,"default":"10"},
  {"key":"corruption","label":"Corruption","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"wrath","label":"Wrath","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"glory","label":"Glory","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"ruin","label":"Ruin","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"wealth","label":"Wealth Tier","type":"number","category":"resource","min":1,"max":5,"default":"2"},
  {"key":"xp","label":"XP","type":"number","category":"resource","min":0,"max":9999,"default":"0"},
  {"key":"talents","label":"Talents","type":"textarea","category":"notes"},
  {"key":"powers","label":"Psychic Powers","type":"textarea","category":"notes"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'wrath_glory';

-- 12. blades
UPDATE rulesets SET schema_json = '[
  {"key":"playbook","label":"Playbook","type":"text","category":"identity","options":["Cutter","Hound","Leech","Lurk","Slide","Spider","Whisper"]},
  {"key":"heritage","label":"Heritage","type":"text","category":"identity","options":["Akoros","The Dagger Isles","Iruvia","Severos","Skovlan","Tycheros"]},
  {"key":"background","label":"Background","type":"text","category":"identity","options":["Academic","Labor","Law","Trade","Military","Underworld"]},
  {"key":"vice","label":"Vice","type":"text","category":"identity","options":["Faith","Gambling","Leisure","Obligation","Pleasure","Stupor","Weird"]},
  {"key":"hunt","label":"Hunt","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"study","label":"Study","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"survey","label":"Survey","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"tinker","label":"Tinker","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"finesse","label":"Finesse","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"prowl","label":"Prowl","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"skirmish","label":"Skirmish","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"wreck","label":"Wreck","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"attune","label":"Attune","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"command","label":"Command","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"consort","label":"Consort","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"sway","label":"Sway","type":"number","category":"skill","min":0,"max":4,"default":"0"},
  {"key":"stress","label":"Stress","type":"number","category":"track","max":9,"default":"0"},
  {"key":"trauma","label":"Trauma","type":"number","category":"track","max":4,"default":"0"},
  {"key":"coin","label":"Coin","type":"number","category":"resource","min":0,"max":10,"default":"2"},
  {"key":"stash","label":"Stash","type":"number","category":"resource","min":0,"max":100,"default":"0"},
  {"key":"load","label":"Load","type":"number","category":"resource","min":0,"max":6,"default":"3"},
  {"key":"xp_insight","label":"XP Insight","type":"number","category":"resource","min":0,"max":8,"default":"0"},
  {"key":"xp_prowess","label":"XP Prowess","type":"number","category":"resource","min":0,"max":8,"default":"0"},
  {"key":"xp_resolve","label":"XP Resolve","type":"number","category":"resource","min":0,"max":8,"default":"0"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'blades';

-- 13. paranoia
UPDATE rulesets SET schema_json = '[
  {"key":"full_name","label":"Full Name","type":"text","category":"identity"},
  {"key":"sector","label":"Sector","type":"text","category":"identity","options":["ALF","BRT","DEN","GRN","MEL","PLC","RED","VLT"]},
  {"key":"security_clearance","label":"Clearance","type":"text","category":"identity","options":["INFRARED","RED","ORANGE","YELLOW","GREEN","BLUE","INDIGO","VIOLET","ULTRAVIOLET"],"default":"INFRARED"},
  {"key":"management_style","label":"Mgmt Style","type":"text","category":"identity","options":["Authoritarian","Bureaucratic","Paranoid","Obsequious"]},
  {"key":"power_group","label":"Power Group","type":"text","category":"identity","options":["Armed Forces","CPU","HPD&MC","IntSec","PLC","R&D","Tech Services"]},
  {"key":"secret_society","label":"Secret Society","type":"text","category":"identity","options":["Anti-Mutant","Communists","FCCC-P","Free Enterprise","Humanists","Mystics","Pro Tech","Romantics"]},
  {"key":"violence","label":"Violence","type":"number","category":"attribute","min":1,"max":6,"default":"3"},
  {"key":"treachery","label":"Treachery","type":"number","category":"attribute","min":1,"max":6,"default":"3"},
  {"key":"happiness","label":"Happiness","type":"number","category":"attribute","min":1,"max":6,"default":"3"},
  {"key":"straight","label":"Straight","type":"number","category":"attribute","min":1,"max":6,"default":"3"},
  {"key":"moxie","label":"Moxie","type":"number","category":"attribute","min":1,"max":6,"default":"3"},
  {"key":"credits","label":"Credits","type":"number","category":"resource","min":0,"max":999,"default":"50"},
  {"key":"clone_number","label":"Clone #","type":"number","category":"resource","min":1,"max":99,"default":"1"},
  {"key":"treason_points","label":"Treason Pts","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'paranoia';

-- 14. dune
UPDATE rulesets SET schema_json = '[
  {"key":"archetype","label":"Archetype","type":"text","category":"identity","options":["Analyst","Athlete","Commander","Courtier","Duelist","Empath","Envoy","Herald","Infiltrator","Messenger","Protector","Scholar","Scout","Sergeant","Smuggler","Spy","Steward","Strategist","Tactician","Warrior"]},
  {"key":"house","label":"House","type":"text","category":"identity","options":["Atreides","Harkonnen","Corrino","Ordos","Richese","Fenring","Vernius","Moritani","Hundro","Wallach"]},
  {"key":"role","label":"Role","type":"text","category":"identity","options":["Ruler","Heir","Consort","Advisor","Spymaster","Marshal","Swordmaster","Envoy","Treasurer","Scholar","Councilor","Warmaster","Chief Physician"]},
  {"key":"faction","label":"Faction","type":"text","category":"identity","options":["House Noble","Bene Gesserit","Spacing Guild","Fremen","Mentat","Suk Doctor","Swordmaster of Ginaz","Tleilaxu","Ixian Technician","Smuggler","Landsraad Noble"]},
  {"key":"ambition","label":"Ambition","type":"text","category":"identity"},
  {"key":"drive_statement","label":"Drive Statement","type":"textarea","category":"notes"},
  {"key":"personality_traits","label":"Personality Traits","type":"textarea","category":"notes"},
  {"key":"duty","label":"Duty","type":"number","category":"attribute","min":1,"max":12,"default":"6"},
  {"key":"faith","label":"Faith","type":"number","category":"attribute","min":1,"max":12,"default":"6"},
  {"key":"justice","label":"Justice","type":"number","category":"attribute","min":1,"max":12,"default":"6"},
  {"key":"power","label":"Power","type":"number","category":"attribute","min":1,"max":12,"default":"6"},
  {"key":"truth","label":"Truth","type":"number","category":"attribute","min":1,"max":12,"default":"6"},
  {"key":"battle","label":"Battle","type":"number","category":"skill","min":4,"max":8,"default":"5"},
  {"key":"communicate","label":"Communicate","type":"number","category":"skill","min":4,"max":8,"default":"5"},
  {"key":"discipline","label":"Discipline","type":"number","category":"skill","min":4,"max":8,"default":"5"},
  {"key":"move","label":"Move","type":"number","category":"skill","min":4,"max":8,"default":"5"},
  {"key":"understand","label":"Understand","type":"number","category":"skill","min":4,"max":8,"default":"5"},
  {"key":"focuses","label":"Focuses","type":"textarea","category":"notes"},
  {"key":"talents","label":"Talents","type":"textarea","category":"notes"},
  {"key":"assets","label":"Assets","type":"textarea","category":"notes"},
  {"key":"determination","label":"Determination","type":"number","category":"resource","min":0,"max":20,"default":"2"},
  {"key":"advancement","label":"Advancement","type":"number","category":"resource","min":0,"max":99,"default":"0"},
  {"key":"wounds","label":"Wounds","type":"number","category":"track","max":20,"default":"6"},
  {"key":"notes","label":"Notes","type":"textarea","category":"notes"}
]' WHERE name = 'dune';
