// Code generated by genrealtime; DO NOT EDIT.

export const REALTIME_CONTRACT_VERSION = 1 as const

export type RealtimeEvent =
  | { type: 'adventure_updated'; sequence: number; payload: { campaign_id?: number; id?: number; session_id?: number } }
  | { type: 'calendar_updated'; sequence: number; payload: { campaign_id?: number } }
  | { type: 'campaign_closed'; sequence: number; payload: { campaign_id?: number } }
  | { type: 'campaign_config_updated'; sequence: number; payload: { campaign_id?: number } }
  | { type: 'campaign_created'; sequence: number; payload: { campaign_id?: number; name?: string } }
  | { type: 'campaign_deleted'; sequence: number; payload: { campaign_id?: number } }
  | { type: 'campaign_reopened'; sequence: number; payload: { campaign_id?: number } }
  | { type: 'campaign_updated'; sequence: number; payload: { campaign_id?: number; chronicle_night?: number; chronicle_night_start_dow?: number } }
  | { type: 'card_drawn'; sequence: number; payload: { campaign_id?: number; card?: Record<string, unknown>; deck_id?: number; deck_name?: string; draw_index?: number; session_id?: number; total?: number } }
  | { type: 'character_created'; sequence: number; payload: { character_id?: number; name?: string } }
  | { type: 'character_updated'; sequence: number; payload: { character_id?: number; clan?: string; currency_balance?: number; currency_delta?: number; currency_label?: string; data_json?: string; embrace?: boolean; field?: string; id?: number; new_value?: number; portrait_path?: string; predator_type?: string; session_id?: number; xp_cost?: number } }
  | { type: 'combat_ended'; sequence: number; payload: { encounter_id?: number; session_id?: number } }
  | { type: 'combat_started'; sequence: number; payload: { encounter_id?: number; name?: string; session_id?: number } }
  | { type: 'combatant_updated'; sequence: number; payload: { combatant_id?: number; encounter_id?: number; session_id?: number } }
  | { type: 'context_updated'; sequence: number; payload: { campaign_id?: number | null; character_id?: number | null; session_id?: number | null } }
  | { type: 'dice_rolled'; sequence: number; payload: { bestial_fail?: boolean; breakdown?: unknown[]; character_name?: string; expression?: string; hidden?: boolean; hunger_dice?: unknown[]; messy_critical?: boolean; normal_dice?: unknown[]; result?: number; rolls?: unknown[]; session_id?: number; successes?: number } }
  | { type: 'expected_action'; sequence: number; payload: { character_id?: number; character_name?: string; session_id?: number } }
  | { type: 'faction_updated'; sequence: number; payload: { campaign_id?: number; id?: number } }
  | { type: 'item_updated'; sequence: number; payload: { character_id?: number; item_id?: number } }
  | { type: 'map_created'; sequence: number; payload: { campaign_id?: number; map_id?: number } }
  | { type: 'map_fx'; sequence: number; payload: { duration_ms?: number; effect?: string; map_id?: number; x?: number; y?: number } }
  | { type: 'map_pin_added'; sequence: number; payload: { label?: string; map_id?: number; pin_id?: number } }
  | { type: 'message_created'; sequence: number; payload: { character_id?: number | null; content?: string; message_id?: number; role?: string; session_id?: number } }
  | { type: 'npc_stat_updated'; sequence: number; payload: { campaign_id?: number; id?: number } }
  | { type: 'npc_updated'; sequence: number; payload: { npc_id?: number; session_id?: number } }
  | { type: 'objective_updated'; sequence: number; payload: { campaign_id?: number; objective_id?: number } }
  | { type: 'oracle_result'; sequence: number; payload: { is_compulsion?: boolean; result?: string; roll?: number; session_id?: number; table?: string } }
  | { type: 'oracle_rolled'; sequence: number; payload: { result?: string; roll?: number; session_id?: number; table?: string } }
  | { type: 'relationship_updated'; sequence: number; payload: { campaign_id?: number; id?: number } }
  | { type: 'resync_required'; sequence: number; payload: { from_sequence: number; to_sequence: number } }
  | { type: 'secret_revealed'; sequence: number; payload: { campaign_id?: number; category?: string; content?: string; id?: number; session_id?: number; title?: string } }
  | { type: 'secrets_updated'; sequence: number; payload: { campaign_id?: number; id?: number } }
  | { type: 'session_deleted'; sequence: number; payload: { session_id?: number } }
  | { type: 'session_ended'; sequence: number; payload: { session_id?: number } }
  | { type: 'session_started'; sequence: number; payload: { session_id?: number; title?: string } }
  | { type: 'session_updated'; sequence: number; payload: { adventure_id?: number | null; campaign_id?: number; masquerade_integrity?: number; notes?: string; scene_tags?: string; session_id?: number; summary?: string } }
  | { type: 'tension_updated'; sequence: number; payload: { session_id?: number; tension_level?: number } }
  | { type: 'token_moved'; sequence: number; payload: { map_id?: number; token_id?: number; x?: number; y?: number } }
  | { type: 'token_placed'; sequence: number; payload: { map_id?: number; token?: Record<string, unknown> } }
  | { type: 'token_removed'; sequence: number; payload: { map_id?: number; token_id?: number } }
  | { type: 'turn_advanced'; sequence: number; payload: { active_turn_index?: number; encounter_id?: number; round_number?: number; session_id?: number } }
  | { type: 'typing'; sequence: number; payload: { character_id?: number; character_name?: string; session_id?: number; status?: string } }
  | { type: 'world_note_created'; sequence: number; payload: { campaign_id?: number; note_id?: number; title?: string } }
  | { type: 'world_note_revealed'; sequence: number; payload: { campaign_id?: number; id?: number; is_revealed?: boolean; note_id?: number; session_id?: number } }
  | { type: 'world_note_updated'; sequence: number; payload: { campaign_id?: number; note_id?: number } }
  | { type: 'xp_added'; sequence: number; payload: { amount?: number | null; id?: number; note?: string; session_id?: number } }
  | { type: 'xp_spend_suggestions'; sequence: number; payload: { character_id?: number; character_name?: string; current_xp?: number; session_id?: number; suggestions?: unknown[]; xp_label?: string } }
  | { type: 'zone_revealed'; sequence: number; payload: { is_revealed?: boolean; map_id?: number; zone_id?: number; zone_name?: string } }

export type RealtimeSSEEvent =
  | { type: 'delta'; delta: string }
  | { type: 'done' }
  | { type: 'error'; code: string; request_id: string }

const websocketPayloads = {
  adventure_updated: { campaign_id: 'number?', id: 'number?', session_id: 'number?' },
  calendar_updated: { campaign_id: 'number?' },
  campaign_closed: { campaign_id: 'number?' },
  campaign_config_updated: { campaign_id: 'number?' },
  campaign_created: { campaign_id: 'number?', name: 'string?' },
  campaign_deleted: { campaign_id: 'number?' },
  campaign_reopened: { campaign_id: 'number?' },
  campaign_updated: { campaign_id: 'number?', chronicle_night: 'number?', chronicle_night_start_dow: 'number?' },
  card_drawn: { campaign_id: 'number?', card: 'object?', deck_id: 'number?', deck_name: 'string?', draw_index: 'number?', session_id: 'number?', total: 'number?' },
  character_created: { character_id: 'number?', name: 'string?' },
  character_updated: { character_id: 'number?', clan: 'string?', currency_balance: 'number?', currency_delta: 'number?', currency_label: 'string?', data_json: 'string?', embrace: 'boolean?', field: 'string?', id: 'number?', new_value: 'number?', portrait_path: 'string?', predator_type: 'string?', session_id: 'number?', xp_cost: 'number?' },
  combat_ended: { encounter_id: 'number?', session_id: 'number?' },
  combat_started: { encounter_id: 'number?', name: 'string?', session_id: 'number?' },
  combatant_updated: { combatant_id: 'number?', encounter_id: 'number?', session_id: 'number?' },
  context_updated: { campaign_id: 'number|null?', character_id: 'number|null?', session_id: 'number|null?' },
  dice_rolled: { bestial_fail: 'boolean?', breakdown: 'array?', character_name: 'string?', expression: 'string?', hidden: 'boolean?', hunger_dice: 'array?', messy_critical: 'boolean?', normal_dice: 'array?', result: 'number?', rolls: 'array?', session_id: 'number?', successes: 'number?' },
  expected_action: { character_id: 'number?', character_name: 'string?', session_id: 'number?' },
  faction_updated: { campaign_id: 'number?', id: 'number?' },
  item_updated: { character_id: 'number?', item_id: 'number?' },
  map_created: { campaign_id: 'number?', map_id: 'number?' },
  map_fx: { duration_ms: 'number?', effect: 'string?', map_id: 'number?', x: 'number?', y: 'number?' },
  map_pin_added: { label: 'string?', map_id: 'number?', pin_id: 'number?' },
  message_created: { character_id: 'number|null?', content: 'string?', message_id: 'number?', role: 'string?', session_id: 'number?' },
  npc_stat_updated: { campaign_id: 'number?', id: 'number?' },
  npc_updated: { npc_id: 'number?', session_id: 'number?' },
  objective_updated: { campaign_id: 'number?', objective_id: 'number?' },
  oracle_result: { is_compulsion: 'boolean?', result: 'string?', roll: 'number?', session_id: 'number?', table: 'string?' },
  oracle_rolled: { result: 'string?', roll: 'number?', session_id: 'number?', table: 'string?' },
  relationship_updated: { campaign_id: 'number?', id: 'number?' },
  resync_required: { from_sequence: 'number', to_sequence: 'number' },
  secret_revealed: { campaign_id: 'number?', category: 'string?', content: 'string?', id: 'number?', session_id: 'number?', title: 'string?' },
  secrets_updated: { campaign_id: 'number?', id: 'number?' },
  session_deleted: { session_id: 'number?' },
  session_ended: { session_id: 'number?' },
  session_started: { session_id: 'number?', title: 'string?' },
  session_updated: { adventure_id: 'number|null?', campaign_id: 'number?', masquerade_integrity: 'number?', notes: 'string?', scene_tags: 'string?', session_id: 'number?', summary: 'string?' },
  tension_updated: { session_id: 'number?', tension_level: 'number?' },
  token_moved: { map_id: 'number?', token_id: 'number?', x: 'number?', y: 'number?' },
  token_placed: { map_id: 'number?', token: 'object?' },
  token_removed: { map_id: 'number?', token_id: 'number?' },
  turn_advanced: { active_turn_index: 'number?', encounter_id: 'number?', round_number: 'number?', session_id: 'number?' },
  typing: { character_id: 'number?', character_name: 'string?', session_id: 'number?', status: 'string?' },
  world_note_created: { campaign_id: 'number?', note_id: 'number?', title: 'string?' },
  world_note_revealed: { campaign_id: 'number?', id: 'number?', is_revealed: 'boolean?', note_id: 'number?', session_id: 'number?' },
  world_note_updated: { campaign_id: 'number?', note_id: 'number?' },
  xp_added: { amount: 'number|null?', id: 'number?', note: 'string?', session_id: 'number?' },
  xp_spend_suggestions: { character_id: 'number?', character_name: 'string?', current_xp: 'number?', session_id: 'number?', suggestions: 'array?', xp_label: 'string?' },
  zone_revealed: { is_revealed: 'boolean?', map_id: 'number?', zone_id: 'number?', zone_name: 'string?' },
} as const

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function matches(value: unknown, spec: string): boolean {
  const optional = spec.endsWith('?')
  const type = optional ? spec.slice(0, -1) : spec
  if (value === undefined) return optional
  if (type.endsWith('|null') && value === null) return true
  const base = type.replace('|null', '')
  if (base === 'object') return isObject(value)
  if (base === 'array') return Array.isArray(value)
  return typeof value === base
}

export function parseRealtimeEvent(value: unknown): RealtimeEvent | null {
  if (!isObject(value) || typeof value.type !== 'string' || typeof value.sequence !== 'number' || !isObject(value.payload)) return null
  const spec = websocketPayloads[value.type as keyof typeof websocketPayloads]
  if (!spec) return null
  for (const [name, type] of Object.entries(spec)) {
    if (!matches(value.payload[name], type)) return null
  }
  return value as RealtimeEvent
}
